### ISSUE TITLE
Oh no, an error occurred: 403 Forbidden. Try again later!

### ISSUE THREAD

**Issue by Overtime2005** [dragonfire535/xiao#42]
**Please describe the problem you are having in as much detail as possible:**

every time I run a roleplay command or something that uses an "key" in the .env (I dont have any in there) I get the error (Oh no, an error occurred: 403 Forbidden. Try again later!) so I was just wodering if you could help me get some of the imgur albums and "key" so I can it to work

**Further details:**
- Version: latest
- Priority this issue should have – please be realistic and elaborate if possible:
medium its probably only for me but its still super annoying

- [ ] I found this issue while self-hosting the bot.
  - Node.js version:   node: '12.16.1',
  - Commit hash: idk
![bruh](https://user-images.githubusercontent.com/39917164/80872114-feb07800-8c7d-11ea-8801-8e71bf980518.PNG)

  - Operating system: Windows 10

**Comment by dragonfire535** [comment]
You're receiving this error precisely because you don't have a key set, you kind of need those. The APIs used in those commands require them.

You can find most of the APIs in the [Credits list](https://github.com/dragonfire535/xiao#credit), search "API" and you can probably find a link to most of their pages where you can sign up. As for the Imgur Album IDs, you need to make Imgur albums and put the IDs in there.

If it sounds too hard the best option would be to use the [publicly invitable bot](https://discordapp.com/api/oauth2/authorize?client_id=278305350804045834&permissions=104197313&scope=bot) rather than trying to self-host. Xiao is not designed with self-hosting in mind.
