### ISSUE TITLE
Meme files and commands

### ISSUE THREAD

**Issue by Overtime2005** [dragonfire535/xiao#45]
**Is your feature request related to a problem? Please describe.**

I know you just rejected my pull request and I know that you probably aren’t looking for extra help or anything, but I have made a few new commands, and if you just looking for somebody to help you with new commands and small bug fixes I would really like to help (I don’t have to much to do)

**Describe the ideal solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by dragonfire535** [comment]
Feel free to PR any commands you have, if nothing else I can use them for ideas. I will note that I don't plan on giving anyone else owner/verification status on Xiao anytime soon, so don't expect that to happen.

Something like this is better brought up in the Discord server rather than on this issue tracker.
