### ISSUE TITLE
what r the apis

### ISSUE THREAD

**Issue by Overtime2005** [dragonfire535/xiao#47]
**Please describe the problem you are having in as much detail as possible:**
I have tried every api I can find to get the toxicity command to work. I really don't think its to hard to tell me where I can get the api keys cause what is "GOOGLE_KEY" very undescriptive and unhelpfull 

**Further details:**
- Version:
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I found this issue while self-hosting the bot.
  - Node.js version:
  - Commit hash:
  - Operating system:

**Comment by FirezzzZ** [comment]
go to google developers console and search 
Youtube Data API v3

**Comment by Overtime2005** [comment]
I know the youtube data one I have that, its the GOOGLE_KEY in the .env im struggling to find

**Comment by Overtime2005** [comment]
ok ive got the youtube command working but the toxicity command gives me

Oh no, an error occurred: 403 Forbidden. Try again later!

**Comment by LordHarkon** [comment]
bruh, IIRC, each command have credits, and the credits for this one goes to https://www.perspectiveapi.com/#/start
I don't think it's hard to figure out what API key you need since if you take a look at their websites you'll see they use google to host their API.

**Comment by Overtime2005** [comment]
Thank you I have a much better grasp on how google handles api’s now. Just one more thing though in the .env it says stuff like “Calendar_id” what does that mean?

**Comment by LordHarkon** [comment]
again, if you search for the calendar event, you'll see the credits point towards: https://developers.google.com/calendar/

**Comment by dragonfire535** [comment]
The calendar ID is the email Google uses to subscribe to events in Google calendar.
For example, US Events: `en.usa#holiday@​group.v.calendar.google.com`

**Comment by dragonfire535** [comment]
Also, I'm not trying to be unhelpful when I don't provide steps for every single api. First of all, it would take forever, and not every api in Xiao is just click and go. Some have application processes. It would probably take me a very long time to make a giant tutorial for that, and I have a life outside of Xiao.

Xiao is _not supposed to be self hosted_. I don't care if people do it, but if they do, I expect them to be able to do it themselves. Otherwise, you might as well just use the regular bot. She's public for a reason.

**Comment by dragonfire535** [comment]
https://github.com/dragonfire535/xiao#filling-out-your-env-file I ended up doing this, if you still need help finding any of the API keys.
