### ISSUE TITLE
Economy System/Poker

### ISSUE THREAD

**Issue by Overtime2005** [dragonfire535/xiao#52]
**Is your feature request related to a problem? Please describe.**
I feel like adding an economy system (like dank memers) would be awesome for Xiao

**Describe the ideal solution**

(economy system, gambling, working, inventory with items)
(card based card games : poker) dms you your hand and then Xiao is the dealer

**Describe alternatives you've considered**

**Additional context**
I would be fine without the economy system I just would really like to play poker with my friends

**Comment by dragonfire535** [comment]
An economy system won't ever come to Xiao as I stray away from things that require a database storage system, I prefer commands that don't save any data. So that probably won't happen.

Poker is actually something that's been in the backlog for Xiao for a _long time_. It's just such a complex command that I haven't gotten to it. It'll probably end up happening eventually.

**Comment by dragonfire535** [comment]
There is now a `poker` command in the latest version of Xiao, though keep in mind it is in beta and may not work 100% perfectly. I think I've ironed out most of the bugs with it but if you find any please report them to [the discord server](https://discord.gg/mTr83zt).
