### ISSUE TITLE
Modmail command feature request

### ISSUE THREAD

**Issue by FirezzzZ** [dragonfire535/xiao#55]
A modmail command because i dont see much modmail bots

**Comment by dragonfire535** [comment]
I've never understood exactly what modmail is supposed to be. Is it just basically the `report` command but to a specific channel in that server? Why not just ping the mods instead of having a bot command dedicated to it?

It'd be easy enough to have mods put `<xiao:modmail>` in a channel topic to have that channel receive messages from a `modmail` command, but I'm not sure I see the appeal of such a feature.

**Comment by FirezzzZ** [comment]
should i close?

**Comment by dragonfire535** [comment]
Yeah I don't think I'm going to add it, sorry.
